steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  args:
  - 'gcloud'
  - 'infra-manager'
  - 'deployments'
  - 'apply'
  - 'strict-components-deployment'
  - '--project=gci-techss-gcp-pjnp-01nl165115'
  - '--location=us-central1'
  - '--git-source-repo=https://github.com/mathewnimmy123-sys/gcp-infra-pipeline'                  
  - '--git-source-ref=$COMMIT_SHA'             
  - '--git-source-directory=infra'
  - '--input-values=project_id=gci-techss-gcp-pjnp-01nl165115'
  - '--service-account=projects/gci-techss-gcp-pjnp-01nl165115/serviceAccounts/591592795300-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY