steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  args:
  - 'infra-manager'
  - 'deployments'
  - 'apply'
  - 'strict-components-deployment'
  - '--project=gci-techss-gcp-pjnp-01nl165115'
  - '--location=us-central1'
  - '--git-source-directory=infra'
  - '--service-account=projects/gci-techss-gcp-pjnp-01nl165115/serviceAccounts/591592795300-compute@developer.gserviceaccount.com'

# 👇 ADD THIS SECTION AT THE BOTTOM
options:
  logging: CLOUD_LOGGING_ONLY